component: shipping
params: "CART_ENDPOINT:dev.shipping.cart_endpoint,DB_HOST:dev.rds.endpoint"
# params: "CART_ENDPOINT:dev.shipping.cart_endpoint,DB_HOST:dev.shipping.db_host"

env: dev


schema:
  create: true
  type: mysql


resources:
   limits:
     cpu: 1300m
     memory: 1500Mi
   requests:
     cpu: 1000m
     memory: 1250Mi

